from typing import Protocol


class CodingTools(Protocol):
    """Narrow capability surface exposed to a coding model."""

    def search_text(self, query: str) -> str: ...
    def read_file(self, path: str, start: int | None = None, end: int | None = None) -> str: ...
    def apply_patch(self, patch: str) -> None: ...


class ModelDriver(Protocol):
    """Inference adapter; concrete model backends stay outside the core loop."""

    def locate_and_plan(self, task: object, tools: CodingTools) -> str: ...
    def create_patch(self, task: object, plan: str, tools: CodingTools) -> str: ...
    def repair_patch(self, task: object, diagnostics: tuple[str, ...], tools: CodingTools) -> str: ...
