from typing import Protocol

from .models import ExpectedScope, GitStatus, ProtectedTests, SubTask, Task, VerificationTarget


class CodingTools(Protocol):
    """Narrow capability surface exposed to a coding model."""

    def list_tree(self, path: str = ".", depth: int = 2) -> tuple[str, ...]: ...
    def find_definitions(self, name: str) -> str: ...
    def find_calls(self, name: str) -> str: ...
    def find_imports(self, name: str) -> str: ...
    def find_tests_for(self, symbol_or_path: str) -> str: ...
    def find_structural(self, pattern: str, language: str = "python") -> str: ...
    def search_text(self, query: str) -> str: ...
    def read_file(self, path: str, start: int | None = None, end: int | None = None) -> str: ...
    def git_diff(self) -> str: ...
    def git_status(self) -> GitStatus: ...
    def patch_checkpoint(self) -> int: ...
    def changed_files_since(self, checkpoint: int) -> tuple[str, ...]: ...
    def apply_test_patch(
        self,
        patch: str,
        scope: ExpectedScope | None = None,
        checkpoint: int | None = None,
    ) -> VerificationTarget: ...
    def discard_test_patch(self) -> None: ...
    def freeze_tests(self) -> ProtectedTests: ...
    def apply_production_patch(
        self,
        patch: str,
        protected_tests: ProtectedTests,
        scope: ExpectedScope | None = None,
        checkpoint: int | None = None,
    ) -> None: ...


class ModelDriver(Protocol):
    """Inference adapter; concrete model backends stay outside the core loop."""

    def decompose(self, task: Task, tools: CodingTools) -> str: ...
    def review_decomposition(
        self, task: Task, subtasks: tuple[SubTask, ...], tools: CodingTools
    ) -> str: ...
    def locate_and_plan(self, task: SubTask, tools: CodingTools) -> str: ...
    def create_test_patch(self, task: SubTask, plan: str, tools: CodingTools) -> str: ...
    def create_patch(
        self,
        task: SubTask,
        plan: str,
        tools: CodingTools,
        test_target: VerificationTarget,
        red_diagnostics: tuple[str, ...],
    ) -> str: ...
    def review_implementation(
        self,
        task: SubTask,
        diff: str,
        tools: CodingTools,
        test_target: VerificationTarget,
    ) -> str: ...
    def repair_patch(
        self,
        task: SubTask,
        diagnostics: tuple[str, ...],
        tools: CodingTools,
        test_target: VerificationTarget,
    ) -> str: ...
