from typing import Protocol

from .models import SubTask, Task


class CodingTools(Protocol):
    """Narrow capability surface exposed to a coding model."""

    def search_text(self, query: str) -> str: ...
    def read_file(self, path: str, start: int | None = None, end: int | None = None) -> str: ...
    def apply_test_patch(self, patch: str) -> None: ...
    def apply_patch(self, patch: str) -> None: ...


class ModelDriver(Protocol):
    """Inference adapter; concrete model backends stay outside the core loop."""

    def decompose(self, task: Task, tools: CodingTools) -> str: ...
    def review_decomposition(
        self, task: Task, subtasks: tuple[SubTask, ...], tools: CodingTools
    ) -> str: ...
    def locate_and_plan(self, task: SubTask, tools: CodingTools) -> str: ...
    def create_test_patch(self, task: SubTask, plan: str, tools: CodingTools) -> str: ...
    def create_patch(self, task: SubTask, plan: str, tools: CodingTools) -> str: ...
    def repair_patch(self, task: SubTask, diagnostics: tuple[str, ...], tools: CodingTools) -> str: ...
